variables:
  DEV_REGISTRY: dev-registry.afreecatv.com
  PROD_REGISTRY: docker-registry.afreecatv.com
  TEST_IMAGE: kimpuro/node20-alpine-pnpm:0.1

stages:
  - test
  - test_build
  - image_build


biome_check:
  stage: test
  image: $TEST_IMAGE
  script:
    - pnpm install --frozen-lockfile
    - pnpm biome check .
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  tags:
    - docker
    - aflxcombuild
  only:
    - merge_requests

type_check:
  stage: test
  image: $TEST_IMAGE
  script:
    - pnpm install --frozen-lockfile
    - pnpm tsc --noEmit
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  tags:
    - docker
    - aflxcombuild
  only:
    - merge_requests

test_build:
  stage: test_build
  image: $TEST_IMAGE
  script:
    - pnpm install --frozen-lockfile
    - pnpm build
  tags:
    - docker
    - aflxcombuild
  only:
    - merge_requests

image_build:
  stage: image_build
  script:
    - echo "$DEV_REGISTRY_PASSWORD" | docker login $DEV_REGISTRY -u $DEV_REGISTRY_USER --password-stdin
    - docker buildx build --platform linux/amd64 -t $DEV_REGISTRY/freecap/freecap-web:${CI_COMMIT_SHORT_SHA} .
    - docker push $DEV_REGISTRY/freecap/freecap-web:${CI_COMMIT_SHORT_SHA}
  after_script:
    - docker logout $DEV_REGISTRY
  tags:
    - freecap
  only:
    - main
    - dev